### ISSUE TITLE
"Shorts" videos never dimmed/hidden

### ISSUE THREAD

**Issue by netjeff** [EvHaus/youtube-hide-watched#103]
"Shorts" videos are never dimmed/hidden because YT doesn't track watchtime on "shorts" videos. The creator on one of my subscriptions has started posting a bunch of shorts, so I'm starting to think about how to handle the shorts.   The best idea I've had so far is to add a new state to the button plus changing the final state:

- State 0 - Shows everything
- State 1 - Watched videos dimmed (shorts not dimmed because never watched)
- State 2 - (new) Watched _and all shorts_ dimmed
- State 3 - (changed) Watched _and all shorts_ hidden

Thought I'd share here to see if there are other ideas to handle shorts.

I'll probably eventually give this idea a try.  I looked into the html, and picking out the "shorts" videos should be straightforward. For me the biggest challenge is getting a new icon for the new state.

**Comment by EvHaus** [comment]
Yeah, I've noticed this as well. Usually what I've been doing is using the "Hide" feature on those once I've watched it to remove it from my view, but it would be great to have the script handle it for you automatically.

I'm not a huge fan of your suggestion though as hiding all Shorts regardless of their watched status goes against the spirit of this extension. You could get into situtions where you forget you're on "State 2" and all your shorts are hidden from view when you genuinely wanted to watch your subscriptions.

The only other idea I have is to make the extension a bit more complex by:
- Monitoring which shorts the user has watched (by tracking which URLs the user has visited). Shorts seem to have URLs in the form `https://www.youtube.com/shorts/<shortId>`. Then
- Storing the watched `shortId` values in some localStorage value
- Hiding any shorts which appear in your list of watched `shortId`. It looks like the video DOM element have the ID in the `#video-title` element's content

**Comment by netjeff** [comment]
I don't like the built-in "Hide" because there's now way to "un-Hide".

I mostly run with "dimmed" rather than "hidden", but agree that for those who run with mostly "hidden" my initial suggestion probably not so good.  I still might give it a try in my repo clone.

Tracking urls in localStorage is definitely the ultimate, and would also help with #30 not just this issue about "Shorts".  I probably don't have the time to attempt this one, but would definitely use if this ever happens.

**Comment by lobbin** [comment]
Shorts really annoy me, but perhaps there should be a second toggle for the shorts?
* State 0 - show all shorts
* State 1 - dim all shorts
* State 2- hide all shorts

**Comment by netjeff** [comment]
FYI, 

I've got a solid draft of @lobbin's suggested _separate toggle button for shorts_, committed in my fork's branch https://github.com/netjeff/youtube-hide-watched/tree/HandleShorts

I'm not quite ready to submit a pull request yet, I want to run with it for a little while to be sure the second button is working well.  

Plus some other things that would be nice:

1. Updated README.md.  I'll definitely do this before a pull request
2. Get a better icon for the shorts button in hidden state.  My own svg skills are pretty basic, so my pull request probably will have the slightly clunky icon for shorts hidden.
3. YT mixes shorts with regular videos on only "subscriptions" section.  So current logic ignores all sections except "subscriptions".  So maybe somehow disable the shorts toggle button elsewhere?  Or "lock" the button?  My eventual pull request probably will leave the button clickable (but no effect).
4. My changes are a lot of cut-n-paste duplication, then tweaked.  Probably there is a refactor with less duplication that would be easier to maintain in the long run.  I probably won't attempt a refactor, and submit pull request with current duplication level.

**Comment by EvHaus** [comment]
Looks good @netjeff! I tested and it works well for me.

What do you think about releasing it as a separate user style entirely? Maybe called "YouTube Hide Shorts"? I think it has different enough goal from hiding watched videos.

**Comment by netjeff** [comment]
@EvHaus wrote:

> What do you think about releasing it as a separate user style entirely?

Hmm... on one hand I agree.   From the [current `@description`](https://github.com/EvHaus/youtube-hide-watched/blob/3b9f484136c0370f340ab8289964f07facceab97/main.user.js#L6)  block in the script:   

> Hides **watched videos** from your YouTube subscriptions page.

On my branch it's now more like:

> Hides **stuff** from your YouTube subscriptions page.

Specifically [my branch's current `@description`](https://github.com/netjeff/youtube-hide-watched/blob/0b1e210490a5f49769e99b363b0722ddca14036f/main.user.js#L6) block reads:

> Hides watched videos from your YouTube subscriptions page. **Also lets you hide shorts.**

On the other hand, trying to have a separate user style that still plays well with this one, that sounds like a lot of work.  :-)

Further, I'm optimistic (naively?) that someday YT will update shorts on subscriptions page, and at that point we can remove the "special handling" for shorts.

So unless you're really opposed to a pull request from me, I'd like to continue in that direction.

==============

FYI, just pushed to my [HandleShorts](https://github.com/netjeff/youtube-hide-watched/tree/HandleShorts) branch with much better icon, and fixed the errors/warnings from the workflow.yml.

Next step is to update the README.md, and then I'll be ready to submit a pull request.

**Comment by EvHaus** [comment]
This has been released in v5.0. Nice work @netjeff!

**Comment by netjeff** [comment]
I discovered a way that YT will mark Shorts as Watched, at least from desktop browser.  

I've been clicking each Short from my subscriptions page, which opens new page to view the Short.  Then I've been using browser's back to get back to the subscriptions page.  YT never marks a Short as watched, when viewed this way.

But another way to view is to use the "Queue", which is a temporary list of videos that will play in sequence.  When you hover over a thumbnail, there is an "Add to queue" button, or you can click the "⋮" menu for the option.   When I added a bunch of shorts to the Queue, and they all played in sequence, all the Shorts watched via the queue are now marked as Watched.  

Once a Short is marked by YT as watched, the "normal" button toggles these.

I'm probably going to start getting in the habit of waiting to watch Shorts until there are a few, then add them to the Queue.  This is nicer anyway than clicking each one, considering how "short" they are.

Hopefully someday YT will be consistent and mark Shorts as watched no matter how you play them.  Once that day arrives, no longer any need for Shorts button.
