### ISSUE TITLE
Does not work since recent YouTube style change

### ISSUE THREAD

**Issue by Programie** [EvHaus/youtube-hide-watched#113]
YouTube changed it's style a few days ago. Since then, the script does not work anymore.

The button to show/dim/hide watched videos appears but clicking on it does not change anything in the video list.

My browser console also does not show anything related to that.

Browser: Mozilla Firefox v106.0.2
Script version: v4.4.1
Userscript Manager: Tampermonkey v4.18.0

**Comment by netjeff** [comment]
Still working for me, same versions as you.   Try disabling all other plugins/scripts,  maybe one of those is interfering?

Browser: Mozilla Firefox v106.0.2
Script version: v4.4.1
Userscript Manager: Tampermonkey v4.18.0

**Comment by Programie** [comment]
I tried to debug it a bit and found out that it is only broken on the channel videos page as the CSS class `ytd-grid-renderer` has been changed to `ytd-rich-item-renderer`. Every other page seems to be working.

Changing the code to get watchedItem for `section === 'channel'` from
```
watchedItem = item.closest('.ytd-grid-renderer');
```
to
```
watchedItem = item.closest('.ytd-rich-item-renderer');
```
fixes dimming/hiding the items on the channel page.

**Comment by netjeff** [comment]
> it is only broken on the channel videos page as the CSS class `ytd-grid-renderer` has been changed to `ytd-rich-item-renderer`. Every other page seems to be working.

From my side I don't see a CSS change on channel videos pages.  

For example, BBC's channel video page (https://www.youtube.com/c/BBCNews/videos) still has class `ytd-grid-renderer`, and the button still works.

![window](https://user-images.githubusercontent.com/3266932/198842959-3ee3d5a5-8f7f-4ac8-9516-c5a2fa0d1a0b.png)

**Comment by netjeff** [comment]
Interesting.  My account is YT Premium.  If I logout, I get the newer CSS.  Looks like YT might be in the middle of a phased rollout, with YT Premium getting the updates later?
