### ISSUE TITLE
Extension not working with new YouTube interface

### ISSUE THREAD

**Issue by m-minasyan** [EvHaus/youtube-hide-watched#145]
Dear EvHaus,

I have been using your extension for quite some time now, and I must say it has been a real lifesaver for me. It has made it so much easier for me to find new content to watch on YouTube by hiding the videos that I have already seen.

However, recently, I have noticed that the extension is not working as expected with the new YouTube interface. The watched videos are no longer being hidden, and I am having trouble navigating through my feed. I have tried to uninstall and reinstall the extension, but it didn’t help.

I am writing to you to request your assistance with this issue. Could you please look into this and provide a solution? I would really appreciate it if you could update the extension to be compatible with the new YouTube interface.

Thank you so much for your time and effort in developing this extension. I hope to hear back from you soon.

Best regards,
Mihran

**Comment by ccardonaguillen** [comment]
Same here. It was working perfectly fine yesterday but apparently Youtube changed their interface and it stopped working. It might probably be due to them renaming some class so it should be an easy fix.

Thank you for this wonderful script, it's so good it has made it extremely difficult for me to use Youtube without it.

**Comment by EvHaus** [comment]
Thanks for report. I'm not able to reproduce the problem yet. YouTube must be rolling out its updates gradually. As soon as I can reproduce the failure consistently, I'll release a fix.

**Comment by m-minasyan** [comment]
@EvHaus
You’re welcome! It’s possible that the issue is not affecting all users or that YouTube is still in the process of rolling out the updates. I appreciate your attention to this matter and your commitment to resolving the problem. Please keep me updated on your progress, and let me know if there is anything else I can do to assist you.

**Comment by jantman** [comment]
I just found this extension today and love it. It's working fine for me currently; I'm in the US southeast (Atlanta, GA) and a YouTube Premium subscriber. Not sure how they're rolling the update out (geographically, or random, or user hash or something) but maybe that info helps.

**Comment by korishan** [comment]
Just wanting to add that I've updated to the latest version of the script and it's not working for me. The already viewed videos aren't being greyed out properly.
I really love this script and it's great to have. makes navigating what I've already seen so much easier, especially when subbed to loads of channels.

I have latest version of Firefox and Tampermonkey

**Comment by korishan** [comment]
awwww heck,  nevermind. It works just fine!!!  It's been so long since I've installed and "activated" it, I completely forgot about the 'eye' button  ::facepalm:: 

It works just fine for me  😜

**Comment by EvHaus** [comment]
Just released version 5.1 that fixes #157. I wonder if it's the same issue as this. Can you give a try and let me know?
