### ISSUE TITLE
Add the ability to only hide fully watched videos.

### ISSUE THREAD

**Issue by dpeter99** [EvHaus/youtube-hide-watched#156]
I would like to have the ability to hide only the videos that I have fully watched. And keep the ones shown that I haven't finished watching fully

**Comment by EvHaus** [comment]
Yeah, that should be possible. We can convert [this variable](https://github.com/EvHaus/youtube-hide-watched/blob/master/main.user.js#L32) into a userscript option.

**Comment by EvHaus** [comment]
This has been added in version 5.3.

You can now go to Greasemonkey, choose "Settings, and change threshold from 10 to 100. Save. Then refresh YouTube.
