### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by kretcee** [EvHaus/youtube-hide-watched#157]
it doesnt work on subscriptions page anymore.

**Comment by EvHaus** [comment]
Works for me. What isn't working for you?

**Comment by solaristhesun** [comment]
For me it doesn't hide anything anymore in the subscription grid layout. The grid layout design changed I think. There are only 3 columns now. It was 4 or 5 columns before. In the list layout, it is still working.

**Comment by EvHaus** [comment]
Ah yes -- I see the problem in the grid layout. Will fix!

**Comment by EvHaus** [comment]
Just released version 5.1 that should fix this. Can you please give it a try?

**Comment by kretcee** [comment]
It still doesnt hide the shorts on subscriptions page

**Comment by EvHaus** [comment]
Thanks! I just released version 5.2 that should also fix the Shorts button.
