### ISSUE TITLE
Shorts not hidden.

### ISSUE THREAD

**Issue by tordenflesk** [EvHaus/youtube-hide-watched#160]
"hidden"
![](https://i.imgur.com/e7ijAEU.png)

"Dimmed":
![](https://i.imgur.com/FUQ2RlR.png)

Waterfox Classic, Violentmonkey v2.14.0, script 5.2

**Comment by netjeff** [comment]
Working fine for me with Firefox v114, and Tampermonkey v4.18.1.

I notice that @tordenflesk is using [WaterFox Classic](https://www.waterfox.net/docs/faq) (WFC, based on Firefox v57) and [Violentmonkey](https://violentmonkey.github.io/) (VM).  This combination of WFC+VM is probably rare.  

Possible causes of this script working with FF+TM, but problems with WFC+VM:
- a subtle bug in this script that manifests only on WFC+VM
- this script depends on behavior that WFC+VM does not provide.  
- a bug with WFC+VM when running this script

**Comment by tordenflesk** [comment]
Worked fine until recently.

**Comment by BogudanPro** [comment]
Author of YTPEF here.

Can you list what elements do you apply classes with `display` property to?

My current list is:

* `div#contents.ytd-rich-grid-renderer`
* `ytd-rich-grid-row.ytd-rich-grid-renderer`
* `ytd-rich-grid-row.ytd-rich-grid-renderer > div`
* `ytd-rich-item-renderer:not(.YT-HWV-WATCHED-HIDDEN)`

The last one was enough until (I think) commit 56ac7ed. Unfortunately, can't get shorts on main page for any tests (spent more than one hour and got 0 of them).

**Comment by netjeff** [comment]
@BogudanPro asked:
> Can you list what elements do you apply classes with `display` property to?

YTHWV finds "watched" elements like this:

```javascript
document.querySelectorAll('.ytd-thumbnail-overlay-resume-playback-renderer');
```

It finds "shorts" elements, only on _Subscriptions_ page, like this:

```javascript
document.querySelectorAll('[overlay-style=SHORTS]');
```

YTHWV finally applies the following classes to the items above

```css
.YT-HWV-WATCHED-HIDDEN { display: none !important }
.YT-HWV-WATCHED-DIMMED { opacity: 0.3 }
.YT-HWV-SHORTS-HIDDEN  { display: none !important }
.YT-HWV-SHORTS-DIMMED  { opacity: 0.3 }
```

See also the full YTHWV userscript code in [main.user.js](https://github.com/EvHaus/youtube-hide-watched/blob/master/main.user.js)

@BogudanPro wrote:
> Unfortunately, can't get shorts on main page

Yes.  While adding"shorts" to YTHWV (#129), I found that shorts appear only on the _Subscriptions_ page.  The YTWHV script looks only on _Subscriptions_ for "shorts".

**Comment by BogudanPro** [comment]
Found the issue. Have not accounted for `.YT-HWV-SHORTS-HIDDEN` class. Script update 2.23.2 should solve it.

**Comment by EvHaus** [comment]
Thanks @BogudanPro. I'll close this issue.
