### ISSUE TITLE
Broken and doesn't work at all

### ISSUE THREAD

**Issue by Goury** [EvHaus/youtube-hide-watched#164]
Script error in [Greasemonkey script https://www.haus.gg//YouTube: Hide Watched Videos; version 5.3]: [YouTube: Hide Watched Videos:1477:19](user-script:https%3A//www.haus.gg//YouTube%3A%20Hide%20Watched%20Videos)
ReferenceError: GM_registerMenuCommand is not defined

Firefox 113

**Comment by Goury** [comment]
Commenting out that line does make it work, but I don't believe it's the best solution.
However, please at least temporary try to catch it and not just crash the whole script.

**Comment by Goury** [comment]
4.11 made at 28 Jan 2021, Firefox says there are no updates.
It was working nicely all this time.

**Comment by jas32096** [comment]
In the meantime, you can use my fork: https://github.com/EvHaus/youtube-hide-watched/pull/163

**Comment by EvHaus** [comment]
I'll get a fix out for this today

**Comment by EvHaus** [comment]
Fixed in v5.4 of the script.

Turns out GreaseMonkey and TamperMonkey have [different APIs](https://github.com/greasemonkey/greasemonkey/issues/3158). 🙄
