### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by inoah1** [EvHaus/youtube-hide-watched#17]
The script is not hiding watch youtube videos on the subscription list.

![image](https://user-images.githubusercontent.com/2716493/34328705-296dacea-e8b4-11e7-8aa1-464fcefc29e5.png)

**Comment by EvHaus** [comment]
You have the script disabled. Press the little Eye icon in the top right menu.

![capture](https://user-images.githubusercontent.com/226640/34329161-9ea98d72-e8a9-11e7-8133-32de55810d8c.PNG)

**Comment by inoah1** [comment]
Thank you, but could you add that to the installation instructions. I thought all I needed to do was install the script and refresh youtube.
Didn't notice the button.

**Comment by EvHaus** [comment]
Added to README.
