### ISSUE TITLE
Youtube Hide Watch doesn't work on Safari on Mac

### ISSUE THREAD

**Issue by mc-hamster** [EvHaus/youtube-hide-watched#188]
Hi,

Youtube Hide Watch doesn't work on Safari on Mac. Attached is a screen shot of my javascript debug window.

I'm running:
Safari Version 17.0 (19616.1.27.211.1) 
Youtube Hide Watch Version 5.11
Userscripts Safari Version 4.4.3 (74)

<img width="1529" alt="image" src="https://github.com/EvHaus/youtube-hide-watched/assets/12804989/e308d31e-23f0-4eb7-aa1e-348ad2370f5f">

**Comment by mc-hamster** [comment]
Please let me know if there's any other information you need or if you'd like me to try anything out.

**Comment by jas32096** [comment]
https://github.com/EvHaus/youtube-hide-watched/pull/163

**Comment by mc-hamster** [comment]
> #163

Yes!

**Comment by EvHaus** [comment]
Just released v6 of the script which should fix the Safari problem.
