### ISSUE TITLE
Not working for https://www.youtube.com/channel/<ID>/videos URL

### ISSUE THREAD

**Issue by gkrystev** [EvHaus/youtube-hide-watched#19]
I just noticed that when you are in videos section for specific channel, if the channel has a Channel ID instead of User ID, i.e. the URL is youtube.com/channel/..../videos instead of youtube.com/user/..../videos, the script does't work.

A simple fix is to replace line 163 from this:
            } else if (window.location.href.match(/.*\/user\/.+\/videos/)) {
to this:
            } else if (window.location.href.match(/.*\/(user|channel)\/.+\/videos/)) {

**Comment by EvHaus** [comment]
Good catch. Fixed in v2.8
