### ISSUE TITLE
[Feature Request] Don't hide unfinished videos

### ISSUE THREAD

**Issue by Lokiamis** [EvHaus/youtube-hide-watched#193]
If possible, I'd like to be able to avoid hiding videos that are only partially watched - a few seconds of watch progress will cause it to be hidden right now.

**Comment by jas32096** [comment]
![Screenshot 2023-11-15 at 10 28 35 AM](https://github.com/EvHaus/youtube-hide-watched/assets/5062225/cd748036-9b78-4721-a4f5-3a09124260ad)

This is configurable via the settings. Set it to 100%, to completely disable
