### ISSUE TITLE
Watched videos are not beeing removed

### ISSUE THREAD

**Issue by marian-bielcik** [EvHaus/youtube-hide-watched#24]
Hello,
watched videos on the "Youtube main page" or in "Up next" section are not beeing hidden in the new youtube material design.

Reason: 
In the function **addClassToWatchedRows** is the identifier of the "to be removed" row wrong: `row = item.closest('ytd-video-renderer');`. 

Fix:
The filter-parameter of the `closest` method should be `ytd-grid-video-renderer` for "main Youtube page" and `ytd-compact-video-renderer` for "Up next" section.

My quick and dirty solution:
`} else {`
`row = item.closest('ytd-compact-video-renderer');`
`if (!row)`
`row = item.closest('ytd-grid-video-renderer');`
`}`

**Comment by EvHaus** [comment]
Thanks for reporting the issue and identifying the fix. I've just published v3.0.0 which should fix the problem.
