### ISSUE TITLE
[feature request] Hide watched shorts in the subscription page.

### ISSUE THREAD

**Issue by KenKaneki73985** [EvHaus/youtube-hide-watched#244]

**Comment by EvHaus** [comment]
You can hide shorts entirely using the "Hide Shorts" button:

![Kapture 2024-08-22 at 21 00 41](https://github.com/user-attachments/assets/dd9e128c-38ae-4fb1-b5d5-49375f795c23)

Just to confirm, you want to keep Shorts visible but want only watched shorts hidden?

**Comment by KenKaneki73985** [comment]
@EvHaus What I meant to say is -- shorts on the uploader's channel.
I want to hide watched shorts on the channel page.

https://i.imgur.com/lL0PERX.mp4

**Comment by bigcheesesteak** [comment]
Shorts are already hidden or dimmed on the home tab of a channel with this script. 
Why would you want to hide shorts if you specifically clicked on the shorts tab?

**Comment by EvHaus** [comment]
Going to close this one. It feels strange to me to hide shorts when you explicitly go to the "Shorts" tab.
