### ISSUE TITLE
Shorts not being dimmed or hidden anymore

### ISSUE THREAD

**Issue by vodkapmp** [EvHaus/youtube-hide-watched#248]
I've noticed over the last week or so that shorts aren't hidden or dimmed anymore.
This goes for both the scubscriptions and recommended pages.

What can I do to help debug this? It happens on multiple machines for me, both in firefox and chrome.

**Comment by vodkapmp** [comment]
The fix in #249 solves the problem.

**Comment by Goury** [comment]
Affects me too

**Comment by EvHaus** [comment]
I'm still not able to reproduce this as YouTube hasn't rolled out the changes for my account, but I've merged the fix in #249. Hopefully this fixes it for you guys. Released in v6.6

**Comment by netjeff** [comment]
It's working for me now.  Thanks!
