### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by netjeff** [EvHaus/youtube-hide-watched#25]
Looking at the [recommended community standards](https://github.com/EvHaus/youtube-hide-watched/community), it suggests adding a license.   With multiple committers a license helps reduce misunderstanding from future committers.  How about adding the MIT license, or even "The Unlicense" aka public domain?  The [repo's community page](https://github.com/EvHaus/youtube-hide-watched/community) has a "Propose" button for license that makes it really easy to add one.

**Comment by EvHaus** [comment]
LICENSE file added.
