### ISSUE TITLE
Doesn't work with Simple YouTube Age Restriction Bypass

### ISSUE THREAD

**Issue by FahadBinHussain** [EvHaus/youtube-hide-watched#257]
The script doesnt work (No UI), if enabled along with [Simple YouTube Age Restriction Bypass](https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass))

**Comment by EvHaus** [comment]
Thanks for the report, but integration/co-existence with other userscripts is not something I think I'd be willing to support.
