### ISSUE TITLE
The "Up Next" video not handled

### ISSUE THREAD

**Issue by netjeff** [EvHaus/youtube-hide-watched#40]
In YT's list of recommended videos while watching a video, the first video aka "Up Next" is not handled when already watched.  Not sure why YT's recommendation algorithm would suggest the "up next" to be an already watched.  But clearly possible because I've seen this occasionally.

Fixing could be tricky.  I'm sure detection is straightforward.  But what to do next is trickier.  If the Up Next follows regular logic, it would be entirely hidden when button says to entirey hide.  But that would probably look weird.  So seems like Up Next should be at most greyed out when watched? 

I think it's rare enough that I don't have any plans to work on this.  But thought I would open an issue just in case anyone else was interested in making changes.

**Comment by EvHaus** [comment]
Yup. I'm aware of this issue. I deliberately ignored the "Up Next" specifically because of the uncertainty of what to do if the next video is watched (and hidden). I think graying them out is an okay solution. Or maybe adding a "Watched" label on it to make it visually clear.

**Comment by EvHaus** [comment]
Closing. YouTube has reworked how their "Up Next" section is rendered and I don't think this request is valid anymore.
