### ISSUE TITLE
show/hide the sidebar recommendations

### ISSUE THREAD

**Issue by barn852** [EvHaus/youtube-hide-watched#61]
I really would like exactly the same button with show/hide the sidebar recommendations, nothing more. Probably it's much easier, but I can't do it. Can you make it please? 

I tried to modify this, but doesn't really work: https://greasyfork.org/en/scripts/408887-youtube-hide-watched-videos/discussions/90432

I also have a FF add-on YT Clean (it does exactly what I want, except it doesn't remember the toggle stage), but I would like a button on the youtube page instead of the FF toolbar.

**Comment by EvHaus** [comment]
You want to hide all recommendations, or just the watched ones?

**Comment by barn852** [comment]
The whole recommendations block (#related section). That all.

**Comment by EvHaus** [comment]
Will reply in your StackOverflow.
