### ISSUE TITLE
New changes to Youtube's CSS

### ISSUE THREAD

**Issue by CaspianRoach** [EvHaus/youtube-hide-watched#76]
In a baffling move, Youtube team has decided to insert "row elements" inside their main container flexbox on the frontpage to encompass the video items 4 at a time. This stops this script from working correctly, because removed elements no longer affect the row container, which is set to partition space for 4 items regardless of whether or not they are actually displayed.

I have fixed it for myself by using the following CSS rules in my browser:

    #contents.ytd-rich-grid-renderer{display:block; margin-left: 16px;}  
    .ytd-rich-grid-renderer:first-child{margin-left:0;}  
    .ytd-rich-grid-renderer{width: auto; display: inline; font-size:0;}  
    ytd-rich-grid-row #contents.ytd-rich-grid-row{display: inline; vertical-align:top; margin: 0;}  
    ytd-rich-item-renderer{width: 256px; display: inline-block; vertical-align:top;}

Effectively breaking the now-useless declaration of flexbox (what were they thinking???) and reverting it to a block of inline elements, which lets hidden elements be removed entirely. Note that this solution will not work for everybody since I hard-coded the width of the individual video element to 256px to fit 6 videos on a row. For a general solution, width calculated by percentages or calc() will have to be used.

~~Another point of note is the 'margin-left:-2px' line, this is to (crudely) fix the space (literal space element) that is inserted by browsers between inline elements if there are any line breaks or spaces in the HTML code. The 2 solutions to solve that is to either collapse the elements in the HTML document together (not possible as we do not control it), or set the font-size of the place between elements to 0, which is kinda hacky. Using negative margin of 2px coincides with the width of a space in my browser, but it will not be the same for every browser, so I am unsure how would you solve it for everybody.~~

**Comment by CaspianRoach** [comment]
I discovered that my 'margin-left:-2px' hack doesn't work for full 4-video rows that are hidden by the script (the effect compounds and ends up moving the next visible row further than normal), so I replaced it with

`font-size:0`

in the same place instead. Luckily, the font sizes are declared further down into the video card elements, so this gets correctly overwritten in places where text is and this solves the inline-space issue.

**Comment by CaspianRoach** [comment]
They seem to have reverted the baffling decision to ruin the purpose of the flexbox and the fix is no longer needed, so hurray. Who knows if it's just temporary though, but keep in mind this method as a potential solution if they break it again.

**Comment by EvHaus** [comment]
Thanks for reporting the issue. I am unable to reproduce it at this time, but will keep an eye on it in case this comes back in the future.

**Comment by CaspianRoach** [comment]
The row elements came back again for me, so I had to apply my fix again. Still works fine.

**Comment by CaspianRoach** [comment]
![image](https://user-images.githubusercontent.com/7204157/143194211-a0fd7618-6ddf-4ea5-a826-d34c79d1c86d.png)
here are the row elements i'm talking about for posterity
