### ISSUE TITLE
Script don't work with new youtube design

### ISSUE THREAD

**Issue by fox1047** [EvHaus/youtube-hide-watched#8]

**Comment by EvNaverniouk** [comment]
Yup. I've already started working on it. The new design makes is very tricky and unfortunately, a lot of features will have to be removed as a result.

If you want to try a beta version, copy paste this code into Tampermonkey: https://github.com/EvNaverniouk/youtube-hide-watched/blob/master/main.js

I'm still doing more testing (and waiting for the new design to officially launch for everyone) before pushing out the update to all users.

**Comment by EvHaus** [comment]
I've published 2.0 with support for the new YouTube layout. The old YouTube layout is no longer supported.
