### ISSUE TITLE
Script stops working today. 

### ISSUE THREAD

**Issue by wrexwaz** [EvHaus/youtube-hide-watched#9]
Script stops working today.  Firefox 55.0.3. Youtube with old loock (not this new witch round icons) Yesterday works normaly.

**Comment by EvHaus** [comment]
This script no longer supports the old YouTube. You'll need to enable the new YouTube look. Visit youtube.com/new and opt-in.

**Comment by wrexwaz** [comment]
*But YouTubeCenter and Better Full Dark Theme 2017 (ARC) don't support new
look 😕 Any solution? Yesterday version of Hide Watched? Something? *

2017-08-31 0:12 GMT+02:00 Ev Haus <notifications@github.com>:

**Comment by wrexwaz** [comment]
OK Never mind. I had an old version in backoop (1.2 february 20 2017 works
great)

2017-08-31 0:12 GMT+02:00 Ev Haus <notifications@github.com>:
