### ISSUE TITLE
Random Videos are hidden

### ISSUE THREAD

**Issue by BubiBalboa** [EvHaus/youtube-hide-watched#99]
I'm on Win 11, Firefox 103, Tampermonkey 4.17.6161 , Script Version 4.3.2. I'm not sure any of that matters though since I have had this problem for quite a while now. Months probably.

The script hides random videos on the Subscriptions page and the Home feed. Switching between the pages via the side bar doesn't change this. Reloading the page fixes the problem for a while until it returns. 

A problem which is most likely connected is that the links to the YT channels (clicking the channel name under the video) are mixed up as well. So you click on channel X and channel Y will open. Reloading fixes this as well, temporarily.

**Comment by EvHaus** [comment]
Are you sure the videos it hides are videos you haven't started? YouTube will mark videos you watched even for just a split second as "watched" and the script will hide them.

If not -- have you seen any other pattern to the videos that are being hidden?

**Comment by EvHaus** [comment]
I haven't been able to reproduce the problem. Without a way to make it happen it will be difficult for me to fix it. Let me know if you discover any other information that might be helpful.

**Comment by BubiBalboa** [comment]
Bad news. It wasn't my filter. 

What's weird is that on the "hide" setting, watched videos are completely hidden as intended but random videos are dimmed. That's new. I used to always have it in "hide mode" and there was no random dimming but there was the random hiding of videos. I turned it to dim mode to look for patterns.

I'll keep trying turning off other addons but I can't think of any that are obvious candidates for causing trouble.

**Comment by EvHaus** [comment]
I may have found the problem. I published version 4.4.1 which might fix the problem. Can you give it a try?

**Comment by BubiBalboa** [comment]
I just checked but there is only one version of the script installed. 

I have now updated to 4.4.1. It takes a while until I can be sure if it works or not. If it looks good after like 30min it's probably alright. I'll come back in a few to report the results. Thanks for taking a look at this problem so quickly.

**Comment by BubiBalboa** [comment]
Looking good. Thanks again.
